Challenge.create(image_url: 'https://images.unsplash.com/photo-1521207418485-99c705420785?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: water, description: 'Leaving the tap running when brushing your teeth wastes up to 10L per minute. Our surveys show 8 out of 10 people have changed their habit and are now turning the tap off. Are you helping to make a difference?', title: 'Brush your teeth with the tap off!');
Challenge.create(image_url: 'https://images.unsplash.com/photo-1556228149-d8f523f77b5a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: water, description: 'Around 9% of total household water use goes down the toilet! When you can, choose the half flush when you use the loo. WELS 4 star toilets use 3L for half flush and 4.5 for full flush.', title: 'Reduce water waste, choose the half flush!');
Challenge.create(image_url: 'https://images.unsplash.com/photo-1561361398-d1f7b6cfee79?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: water, description: 'Almost 1/4 of household water is used in the shower. Cutting your shower time by just 2 minutes can result in a water saving of up to 30%. Try using a shower timer or your favourite 4 minute song to time your showers.', title: 'Save water and energy by reducing shower times to 4 minutes.');

Challenge.create(image_url: 'https://images.unsplash.com/photo-1582765114728-428aa4d1ff36?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: waste,description: 'Water bottles and paper coffee cups are huge wastes of material. Buy a durable water bottle and a cute coffee thermos so you can take your beverages wherever you please. You’ll find yourself feeling a lot more hydrated and a lot less wasteful.', title: 'Stop buying plastic water bottles.');
Challenge.create(image_url: 'https://images.unsplash.com/photo-1563635707796-b4b9d6007a8c?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: waste, description: 'Once you start buying only what you need, take it to the next level by storing food properly, which will extend its life and keep things fresh for as long as possible. Invest in some quality airtight containers for things like baking ingredients, cereals, and other things that can stale quickly. If you buy loose food items from farmer’s markets or bulk bins at stores like Whole Foods, reusable containers are especially important to have in your kitchen.', title: 'Start relying on reusable containers');

Challenge.create(image_url: '', category: energy, description: 'To reduce energy consumption in your home, you do not necessarily need to go out and purchase energy efficient products. Energy conservation can be as simple as turning off lights or appliances when you do not need them. You can also use energy-intensive appliances less by performing household tasks manually, such as hang-drying your clothes instead of putting them in the dryer, or washing dishes by hand. The behavior adjustments that have the highest potential for utility savings are turning down the heat on your thermostat in the winter and using your air conditioner less in the summer. Heating and cooling costs constitute nearly half of an average home’s utility bills, so these reductions in the intensity and frequency of heating and cooling offer the greatest savings.', title: 'Adjust your day-to-day behaviors');
Challenge.create(image_url: 'https://images.unsplash.com/photo-1508920291026-c344bbfca1ab?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: energy, description: '“Phantom loads,” or the electricity used by electronics when they are turned off or in standby mode, are a major source of energy waste. In fact, it is estimated that 75% of the energy used to power household electronics is consumed when they are switched off, which can cost you up to $200 per year. Smart power strips, also known as advanced power strips, eliminate the problem of phantom loads by shutting off the power to electronics when they are not in use. Smart power strips can be set to turn off at an assigned time, during a period of inactivity, through remote switches, or based on the status of a “master” device.', title: 'Use smart power strips');

Challenge.create(image_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQwATm_sNFXqj0GPHfhMpI8Mw0Af8CXyQYAnBMNrbZFuUy4mXB5', category: home, description: 'This will save both the planet and your wallet! Do an energy audit of your home. This will show how you use or waste energy and help identify ways to be more energy efficient.', title: 'Energy Audit');
Challenge.create(image_url: 'https://media.defense.gov/2008/Sep/18/2000678565/780/780/0/080918-F-2580A-001.JPG', category: home, description: 'Did you know that incandescent lights waste 90% of their energy as heat? Instead, use LED lights, these only use a quarter of that energy and can last up to 25 times longer! They might be more expensive, but definitely worth the investments. Switch those bulbs out!', title: 'Change those bulbs!');

Challenge.create(image_url: 'https://cdn.pixabay.com/photo/2019/08/02/19/02/transportation-4380326_960_720.jpg', category: transportation, description: 'Today you are allowed to only take the train, bus or bike to go to work! (the leg wagon is also allowed).', title: 'Only take public transport today!');
Challenge.create(image_url: 'https://upload.wikimedia.org/wikipedia/commons/9/9a/Daimler_4.0_%281990%29_trunk.jpg', category: transportation, description: 'To transport extra weight, you are emitting more gas. You are carrying unnecessary items every day to work and back! Which means that unnecessarily, you are emitting way more than needed. Clean out that trunk, get rid of unnecessary items. You will thank yourself later.', title: '');

Challenge.create(image_url: 'https://images.unsplash.com/photo-1490818387583-1baba5e638af?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60', category: food, description: ' Overeating is a problem for many people.\nMaking sure your portion sizes stay within a healthy range doesn’t just help keep your weight down, it also reduces food waste.\nWhile you may not think twice about scraping the leftover food on your plate into the trash, remember that food waste has a major impact on the environment.\nBeing more mindful of how hungry you actually are and practicing portion control are great ways to reduce food waste.', title: 'Keep Your Serving Sizes in Check');
Challenge.create(image_url: 'https://images.unsplash.com/photo-1582803824122-f25becf36ad8?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: food, description: ' “Sell by” and “expires on” are just two of the many confusing terms companies use on food labels to let consumers know when a product will most likely go bad.\nThe truth is, most food that has just passed its expiration date is still safe to eat.\n“Sell by” is used to inform retailers when the product should be sold or removed from the shelves. “Best by” is a suggested date that consumers should use their products by.\nNeither of these terms means that the product is unsafe to eat after the given date.\nWhile many of these labels are ambiguous, “use by” is the best one to follow. This term means that the food may not be at its best quality past the listed date. A movement is now underway to make the food expiration labeling system more clear for consumers. In the meantime, use your best judgment when deciding whether food that is slightly past its expiration date is safe to eat.', title: 'Understand Expiration Dates');