# generate tips
Tip.create(image_url: 'https://images.unsplash.com/photo-1564518823771-494a12735793?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: water, description: 'Running taps contribute to water waste, running the tap to rinse fresh produce can use up to 10L of water per minute!. Avoid unnecessary waste by putting a plug in the sink or using a bowl when cleaning fruit and veg. The water you collect can be used on your garden.', title: 'Plug the sink or use a bowl when you are washing vegies.');
Tip.create(image_url: 'https://images.unsplash.com/photo-1571781418606-70265b9cce90?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: water, description: 'Showers make up 22% of total household water use. By swapping to water efficient shower heads, households can save up to 20, 000L of water per year. When selecting a shower head look for the stars on the WELS label the more stars, the more water you will save. Also look at the flow rate (litres per minute) as this can vary substantially.', title: 'Swap to a water efficient showerhead.');
Tip.create(image_url: 'https://images.unsplash.com/photo-1510551310160-589462daf284?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60',category: water, description: 'Washing machines account for 16% of all water used inside the average home. Reducing your washing by just one load a week could save almost 2,600L each year! Look to upgrade to a water efficient machine which use half as much water as the older models, less energy and they are much gentler on your clothes!', title: 'Save 50L of water when you reduce your washing by one load a week');

Tip.create(image_url: 'https://images.unsplash.com/photo-1517319725296-466c84bd7d54?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: waste, description: 'Since recycling standards vary from place to place, find out the specific rules for your area.', title: 'Get to know the rules of recycling.');
Tip.create(image_url: 'https://images.unsplash.com/photo-1524778219663-26b4a0ccc132?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: waste, description: 'Description: If your mailbox is overloaded with catalogs and junk mail each day, take a few minutes to cancel subscriptions and stop unsolicited junk mail.', title: 'Cancel unnecessary mail.');

Tip.create(image_url: 'https://images.unsplash.com/photo-1535813547-99c456a41d4a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: energy, description: 'Traditional incandescent light bulbs consume an excessive amount of electricity and must be replaced more often than their energy efficient alternatives. Halogen incandescent bulbs, compact fluorescent lights (CFLs), and light-emitting diode bulbs (LEDs) use anywhere from 25-80% less electricity and last three to 25 times longer than traditional bulbs. Although energy efficient bulbs are more expensive off the shelf, their efficient energy use and longer service lives mean that they cost less in the long run. Energy efficient bulbs are the clear winners in terms of their environmental and financial benefits.', title: 'Replace your light bulbs.');
Tip.create(image_url: 'https://images.unsplash.com/photo-1546610848-7ad7a33af206?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: energy, description: 'Windows are a significant source of energy waste, which can amount to 10-25% of your total heating bill. To prevent heat loss through your windows, you can replace single-pane windows with double-pane ones.\nFor homes in cold regions, gas-filled windows with “low-e” coatings can significantly reduce your heating expenses. In addition, interior or exterior storm windows can reduce unnecessary heat loss by ten to 20 percent. You should especially consider storm windows if your region experiences frequent extreme weather events.\nIn warmer climates, heat gain through windows may be a problem. In addition to minimizing heat loss, low-e coatings on windows can reduce heat gain by reflecting more light and lowering the amount of thermal energy diffused into your home. Depending on the climate where you live, energy efficient windows can save you $20-$95 each year on your utility bills. Window shades, shutters, screens, and awnings can also provide an extra layer of insulation between your home and external temperatures.', title: 'Install energy efficient windows.');

Tip.create(image_url: 'https://images.unsplash.com/photo-1529310399831-ed472b81d589?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1400&q=60', category: home, description: 'We all know that old incandescent light bulbs are very bad for the environment. But how bad are they exactly? Well, it turns out that 90% of their energy consumption is wasted to heat! As supposed to LED lights, which only consumes a quarter of what an incandescent light emits. Also LED’s last up to 25 times longer. They might be more expensive, but they are definitely worth the investment!', title: ' Light bulbs.');
Tip.create(image_url: 'https://upload.wikimedia.org/wikipedia/commons/5/5e/Heat_wave_refresh_it_with_water.jpg', category: home, description: 'According to a new report (https://www.seforall.org/sites/default/files/SEforALL_CoolingForAll-Report_0.pdf) 10 percent of the planet’s warming now comes from cooling technologies. Airconditioning is the main culprit for that. It’s like a vicious cycle: the world is warming up, so we make more use of airconditioning, so we emit more greenhouse gases, so the planet becomes warmer and so forth… So how can we keep cool but avoiding airconditioning? Obviously you can dress lighter, put on a light t-shirt and airy shorts can already help a lot. Also eating lighter cold foods as salads, low-fat diary or even eating spicy, can lower your body temperature. Fans use a lot less electricity, so make use of those! And if you can’t take it anymore, just go to the nearest Starbucks, they have the best airconditioning in town.', title: 'How to keep cool during a heatwave.');

Tip.create(image_url: 'https://i.pinimg.com/originals/30/7c/b5/307cb574a92b913ce2c678a975d5b84b.jpg', category: transportation, description: 'Really really bad! First of all, there is space: A car takes a huge amount of space that is both unnecessary and inconvenient. It also lacks movement in the body, which can make you fat if you don’t do any other physical activity. If you still need to drive, consider the following tips: \n1 Take care of your car\nKeeping tires inflated properly can increase fuel efficiency by 3 percent, making sure your car is properly maintained by another 4 percent. Also don’t forget to remove any unnecessary weight from your car.\n2 Reduce driving by combining errands\n3 On longer trips, turn on cruise control which can save gas\n4 Use less airconditioning when you drive.', title: 'How bad is driving for the environment exactly?');
Tip.create(image_url: 'https://images.unsplash.com/photo-1545922016-87c93aaca2ce?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1400&q=60', category: transportation, description: ' Flying is one of the most polluting things you can do. In 2018 air travel contributed to 2.4% of all global emissions. As international tourism becomes more and more popular and more people can afford air travel to visit further away places, this number is only going to increase. Instead, vacations closer to home can be just as fun! If you do need to travel, consider these tips:\n1 Try to keep layovers to a minimum as landings and takeoffs require more energy.\n2 Go economy class. Business class is responsible for almost 3 times as many emissions as economy because in economy, the flight’s carbon emissions are shared among more passengers. First class can result in nine times more carbon emissions!\n3 if you can’t avoid flying, offset the carbon emissions of your travel.', title: 'Air travel');

Tip.create(image_url: 'https://images.unsplash.com/photo-1576719218362-01af43ab192a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60', category: food, description: 'Most people tend to buy more food than they need.Make a point to use up all the food you purchased during the last trip to the market before buying more groceries. Additionally, try making a list of items that you need to buy and stick to that list. This will help you reduce impulse buying and reduce food waste as well.', title: 'Shop Smart');
Tip.create(image_url: 'https://images.unsplash.com/photo-1545898073-346e42dc7357?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1296&q=60', category: food, description: 'Improper storage leads to a massive amount of food waste. Many people are unsure how to store fruits and vegetables, which can lead to premature ripening and, eventually, rotten produce. For instance, potatoes, tomatoes, garlic, cucumbers and onions should never be refrigerated. These items should be kept at room temperature. Separating foods that produce more ethylene gas from those that don’t is another great way to reduce food spoilage. Ethylene promotes ripening in foods and could lead to spoilage.', title: 'Store Food Correctly');
